spring: 
  datasource:
    url: jdbc:mysql://192.168.0.14:3326/backend
    username: root
    password: test.123
  jpa: 
    hibernate:
      ddl-auto: none
      
server:
  error:
    include-stacktrace: never
    
feign:
  config:
    api: 
      name: sandbox
      url: https://sandbox.ionix.cl
      #se busca el rut
      path: /test-tecnico/search